name: CI & SonarCloud Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  sonar_scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: (Opcjonalnie) Uruchom testy
        run: npm test -- --coverage || true

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1
        with:
          projectKey: ${{ secrets.SONAR_PROJECT_KEY_SERVER }}
          organization: yourOrg
          token: ${{ secrets.SONAR_TOKEN }}
